CREATE TABLE IF NOT EXISTS application_info
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(100) NOT NULL,
    initialized_at      timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO application_info (name)
VALUES ('Chronicles');